---
# Gather packages
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: Install base packages
      apt: pkg="{{ item }}"
      with_items:
          - vim
          - git
          - redis
